### ISSUE TITLE
Wrong apm install command

### ISSUE THREAD

**Issue by BenDiuguid** [bastilian/atom-packages.directory#14]
Hey, awesome work so far!

I noticed a couple of issues with the following pages, where the `apm install` command is slightly off of what it is supposed to be.

`apm install ignore` should be `apm install language-ignore`
http://atom-packages.directory/package/language-ignore/ 

`apm install linter-node-dependencies` should be `apm install atom-linter-node-dependencies`
http://atom-packages.directory/package/atom-linter-node-dependencies/

`apm install slack` should be `apm install slack-ui`
http://atom-packages.directory/package/slack-ui/ 

So far awesome work though!!!

**Comment by bastilian** [comment]
Thanks for reporting this issue!

Very weird issue. It seems that delegating in the decorators results in returning a reference of the attributes rather than the value.

The issue is fixed with a2ec9cd by using non-destructive methods.
It should be live later today when the build has been run again.
